"""new Department index

Revision ID: 5fa0ba2841c8
Revises: 9868dbdb064c
Create Date: 2026-03-05 00:11:10.351570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fa0ba2841c8'
down_revision: Union[str, Sequence[str], None] = '9868dbdb064c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_department_root_name', 'departments', ['name'], unique=True, postgresql_where=sa.text('parent_id IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_department_root_name', table_name='departments', postgresql_where=sa.text('parent_id IS NULL'))
    # ### end Alembic commands ###
